export const CROPS = {
  tomato: {
    id: 'tomato',
    name: 'Tomato',
    seedName: 'Tomato Seeds',
    seedCost: 20,
    energyCost: 1,
    stages: ['🌱', '🪴', '🍃', '🍅'],
    stageLabels: ['Seed', 'Sprout', 'Plant', 'Harvest!'],
    sessionsPerStage: 2,
    harvestCoins: 30,
    color: 'red',
  },
  corn: {
    id: 'corn',
    name: 'Corn',
    seedName: 'Corn Seeds',
    seedCost: 30,
    energyCost: 1,
    stages: ['🌱', '🌿', '🌾', '🌽'],
    stageLabels: ['Seed', 'Small Stalk', 'Tall Stalk', 'Harvest!'],
    sessionsPerStage: 3,
    harvestCoins: 45,
    color: 'yellow',
  },
  potato: {
    id: 'potato',
    name: 'Potato',
    seedName: 'Potato Seeds',
    seedCost: 30,
    energyCost: 1,
    stages: ['🌱', '🍀', '🌿', '🥔'],
    stageLabels: ['Seed', 'Leaves', 'Mature Plant', 'Harvest!'],
    sessionsPerStage: 3,
    harvestCoins: 45,
    color: 'amber',
  },
  cabbage: {
    id: 'cabbage',
    name: 'Cabbage',
    seedName: 'Cabbage Seeds',
    seedCost: 40,
    energyCost: 1,
    stages: ['🌱', '🥬', '🥦', '🥗'],
    stageLabels: ['Seed', 'Sprout', 'Full Cabbage', 'Harvest!'],
    sessionsPerStage: 4,
    harvestCoins: 55,
    color: 'green',
  },
}

export const CROP_LIST = Object.values(CROPS)
