export const WORLDS = [
  {
    id: 'farm',
    name: 'Countryside Farm',
    description: 'Your cozy home farm. Warm soil, open skies, and room to grow.',
    icon: '🌾',
    sessionsRequired: 0,
    bgFrom: 'from-sky-50',
    bgTo: 'to-leaf-50',
    gridBg: 'bg-soil-100/50',
    accentColor: '#22c55e',
    crops: ['tomato', 'corn', 'potato', 'cabbage'],
    unlockHint: 'Always available',
  },
  {
    id: 'zen',
    name: 'Zen Garden',
    description: 'Bamboo groves, koi ponds, and the sound of distant water.',
    icon: '🎋',
    sessionsRequired: 10,
    bgFrom: 'from-teal-50',
    bgTo: 'to-cyan-50',
    gridBg: 'bg-teal-100/40',
    accentColor: '#0d9488',
    crops: ['tomato', 'cabbage'],
    unlockHint: 'Reach 10 focus sessions',
  },
  {
    id: 'rice',
    name: 'Rice Fields',
    description: 'Terraced paddies stretch to the horizon beneath misty mountains.',
    icon: '🌿',
    sessionsRequired: 25,
    bgFrom: 'from-emerald-50',
    bgTo: 'to-green-100',
    gridBg: 'bg-emerald-100/50',
    accentColor: '#059669',
    crops: ['corn', 'potato'],
    unlockHint: 'Reach 25 focus sessions',
  },
  {
    id: 'vineyard',
    name: 'Italian Vineyard',
    description: 'Rolling hills of grape vines, olive trees, and warm afternoon light.',
    icon: '🍇',
    sessionsRequired: 40,
    bgFrom: 'from-purple-50',
    bgTo: 'to-violet-50',
    gridBg: 'bg-purple-100/40',
    accentColor: '#7c3aed',
    crops: ['tomato', 'cabbage'],
    unlockHint: 'Reach 40 focus sessions',
  },
  {
    id: 'tropical',
    name: 'Tropical Island',
    description: 'Coconut palms, colorful parrots, and crystal-clear water.',
    icon: '🌴',
    sessionsRequired: 60,
    bgFrom: 'from-orange-50',
    bgTo: 'to-yellow-50',
    gridBg: 'bg-orange-100/40',
    accentColor: '#ea580c',
    crops: ['corn', 'potato'],
    unlockHint: 'Reach 60 focus sessions',
  },
]

export const WORLDS_MAP = Object.fromEntries(WORLDS.map(w => [w.id, w]))
